### ISSUE TITLE
Actions while being logged in

### ISSUE THREAD

**Issue by satpalsr** [theredsix/cerebellum#10]
Each time it would start a new window where I am logged out of the account.
Example: I want to order USB C cable from amazon so it should just start session from same browser where I am already logged in instead of new session where I have to then login.

**Comment by theredsix** [comment]
You'll need to set a user profile directory for your sessions, log in to your website from that profile, and load it into Selenium as part of your initialization process. 

https://stackoverflow.com/questions/77390094/how-to-use-user-profile-with-seleniumbase
