### ISSUE TITLE
it got an error？

### ISSUE THREAD

**Issue by ChenRenHu** [theredsix/cerebellum#4]
status: 403,
  headers: {
    'cf-ray': '8de2cf14682c20dc-HKG',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    date: 'Wed, 06 Nov 2024 05:50:56 GMT',
    server: 'cloudflare',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding',
    'x-robots-tag': 'none'
  },
  request_id: undefined,
  error: { error: { type: 'forbidden', message: 'Request not allowed' } }
}

**Comment by theredsix** [comment]
Hi @ChenRenHu can you submit a minimum node project for us to recreate this bug?

**Comment by ChenRenHu** [comment]
i just change my api key ，and run npx tsx example/google.ts  ，and it got an error

**Comment by theredsix** [comment]
It appears that Anthropic is rejecting your API key.

**Comment by ChenRenHu** [comment]
It's strange, when I call the SDK separately, it works fine.

**Comment by theredsix** [comment]
Can you try passing in the key explicitly into the `AnthropicPlanner` constructor?
