### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rzrhu** [theredsix/cerebellum#5]
headers: {
    connection: 'keep-alive',
    'content-length': '289',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 06 Nov 2024 06:13:23 GMT',
    server: 'nginx/1.18.0 (Ubuntu)',
    'x-oneapi-request-id': 'B20241106141322547132836VTNqcn4c'
  },
  request_id: undefined,
  error: {
    error: {
      type: 'new_api_error',
      message: 'messages.4: Did not find 1 `tool_result` block(s) at the beginning of this message. Messages following `tool_use` blocks must begin with a matching number of `tool_result` blocks.  (request id: B20241106141322547132836VTNqcn4c)'
    },
    type: 'error'
  }
}

**Comment by theredsix** [comment]
Hi @rzrhu  can you submit a minimum node project for us to recreate this bug?
