### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shenxingqi** [theredsix/cerebellum#7]
**Describe the bug**

MacBook-Pro cerebellum % npx tsx example/google.ts
/Users/PycharmProjects/cerebellum/node_modules/sharp/lib/output.js:163
  const stack = Error();
                ^

Error: Image to composite must have same dimensions or smaller

“My computer is a Mac M3 running version 15.1, and I would like to ask for help with this screenshot error.”.thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by theredsix** [comment]
Hi @shenxingqi for your bug report, what is the resolution of the browser you're launching and may I see your selenium driver configuration?

**Comment by theredsix** [comment]
Patched in v0.1.1
